-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Der_Faux_FPGA_V2_optimized\Z24_circuit.vhd
-- Created: 2022-04-19 09:51:10
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Z24_circuit
-- Source Path: Der_Faux_FPGA_V2_optimized/Der_Faux_FPGA/Z24_circuit
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Der_Faux_FPGA_pkg.ALL;

ENTITY Z24_circuit IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Gvar3_N                           :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        Z24_in                            :   IN    std_logic_vector(45 DOWNTO 0);  -- sfix46_En51
        Z24_out                           :   OUT   std_logic_vector(45 DOWNTO 0)  -- sfix46_En43
        );
END Z24_circuit;


ARCHITECTURE rtl OF Z24_circuit IS

  -- Constants
  CONSTANT LUT_Z24a_data                  : vector_of_signed21(0 TO 31) := 
    (to_signed(16#0A6A85#, 21), to_signed(16#0A6A97#, 21), to_signed(16#0A6A9D#, 21), to_signed(16#0A6AA0#, 21),
     to_signed(16#0A6AA2#, 21), to_signed(16#0A6AA3#, 21), to_signed(16#0A6AA4#, 21), to_signed(16#0A6AA5#, 21),
     to_signed(16#0A6AA5#, 21), to_signed(16#0A6AA5#, 21), to_signed(16#0A6AA6#, 21), to_signed(16#0A6AA6#, 21),
     to_signed(16#0A6AA6#, 21), to_signed(16#0A6AA6#, 21), to_signed(16#0A6AA6#, 21), to_signed(16#0A6AA6#, 21),
     to_signed(16#0A6AA6#, 21), to_signed(16#0A6AA6#, 21), to_signed(16#0A6AA6#, 21), to_signed(16#0A6AA6#, 21),
     to_signed(16#0A6AA6#, 21), to_signed(16#0A6AA6#, 21), to_signed(16#0A6AA5#, 21), to_signed(16#0A6AA5#, 21),
     to_signed(16#0A6AA5#, 21), to_signed(16#0A6AA4#, 21), to_signed(16#0A6AA3#, 21), to_signed(16#0A6AA2#, 21),
     to_signed(16#0A6AA0#, 21), to_signed(16#0A6A9D#, 21), to_signed(16#0A6A97#, 21), to_signed(16#0A6A85#, 21));  -- sfix21 [32]
  CONSTANT LUT_Z24b_data                  : vector_of_signed20(0 TO 31) := 
    (to_signed(-16#7FFC6#, 20), to_signed(-16#7FFE2#, 20), to_signed(-16#7FFEB#, 20), to_signed(-16#7FFF0#, 20),
     to_signed(-16#7FFF3#, 20), to_signed(-16#7FFF5#, 20), to_signed(-16#7FFF6#, 20), to_signed(-16#7FFF7#, 20),
     to_signed(-16#7FFF7#, 20), to_signed(-16#7FFF8#, 20), to_signed(-16#7FFF8#, 20), to_signed(-16#7FFF9#, 20),
     to_signed(-16#7FFF9#, 20), to_signed(-16#7FFF9#, 20), to_signed(-16#7FFF9#, 20), to_signed(-16#7FFF9#, 20),
     to_signed(-16#7FFF9#, 20), to_signed(-16#7FFF9#, 20), to_signed(-16#7FFF9#, 20), to_signed(-16#7FFF9#, 20),
     to_signed(-16#7FFF9#, 20), to_signed(-16#7FFF8#, 20), to_signed(-16#7FFF8#, 20), to_signed(-16#7FFF7#, 20),
     to_signed(-16#7FFF7#, 20), to_signed(-16#7FFF6#, 20), to_signed(-16#7FFF5#, 20), to_signed(-16#7FFF3#, 20),
     to_signed(-16#7FFF0#, 20), to_signed(-16#7FFEB#, 20), to_signed(-16#7FFE2#, 20), to_signed(-16#7FFC6#, 20));  -- sfix20 [32]

  -- Signals
  SIGNAL Gvar3_N_unsigned                 : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL LUT_Z24a_k                       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL LUT_Z24a_out1                    : signed(20 DOWNTO 0);  -- sfix21_En23
  SIGNAL Mult_delay2_out1                 : signed(20 DOWNTO 0);  -- sfix21_En23
  SIGNAL Z24_in_signed                    : signed(45 DOWNTO 0);  -- sfix46_En51
  SIGNAL Product6_mul_temp                : signed(66 DOWNTO 0);  -- sfix67_En74
  SIGNAL Product6_out1                    : signed(45 DOWNTO 0);  -- sfix46_En54
  SIGNAL LUT_Z24b_k                       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL LUT_Z24b_out1                    : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL Mult_delay1_out1                 : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL Delay_Mod10_out1                 : signed(45 DOWNTO 0);  -- sfix46_En51
  SIGNAL Product7_mul_temp                : signed(66 DOWNTO 0);  -- sfix67_En74
  SIGNAL Product7_out1                    : signed(45 DOWNTO 0);  -- sfix46_En54
  SIGNAL Sum4_out1                        : signed(45 DOWNTO 0);  -- sfix46_En43
  SIGNAL Delay_Mod11_out1                 : signed(45 DOWNTO 0);  -- sfix46_En43
  SIGNAL Product8_mul_temp                : signed(65 DOWNTO 0);  -- sfix66_En62
  SIGNAL Product8_out1                    : signed(45 DOWNTO 0);  -- sfix46_En43
  SIGNAL Sum4_stage2_sub_cast             : signed(57 DOWNTO 0);  -- sfix58_En54
  SIGNAL Sum4_stage2_sub_cast_1           : signed(57 DOWNTO 0);  -- sfix58_En54
  SIGNAL Sum4_op_stage2                   : signed(57 DOWNTO 0);  -- sfix58_En54
  SIGNAL Sum4_stage3_add_cast             : signed(58 DOWNTO 0);  -- sfix59_En54
  SIGNAL Sum4_stage3_add_cast_1           : signed(57 DOWNTO 0);  -- sfix58_En54
  SIGNAL Sum4_stage3_add_cast_2           : signed(58 DOWNTO 0);  -- sfix59_En54
  SIGNAL Sum4_stage3_add_temp             : signed(58 DOWNTO 0);  -- sfix59_En54
  SIGNAL Sum4_stage3_cast                 : signed(57 DOWNTO 0);  -- sfix58_En54

BEGIN
  Gvar3_N_unsigned <= unsigned(Gvar3_N);

  
  LUT_Z24a_k <= to_unsigned(16#00#, 5) WHEN Gvar3_N_unsigned = to_unsigned(16#00#, 5) ELSE
      to_unsigned(16#1F#, 5) WHEN Gvar3_N_unsigned = to_unsigned(16#1F#, 5) ELSE
      Gvar3_N_unsigned;
  LUT_Z24a_out1 <= LUT_Z24a_data(to_integer(LUT_Z24a_k));

  Mult_delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Mult_delay2_out1 <= to_signed(16#000000#, 21);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Mult_delay2_out1 <= LUT_Z24a_out1;
      END IF;
    END IF;
  END PROCESS Mult_delay2_process;


  Z24_in_signed <= signed(Z24_in);

  Product6_mul_temp <= Mult_delay2_out1 * Z24_in_signed;
  
  Product6_out1 <= "0111111111111111111111111111111111111111111111" WHEN (Product6_mul_temp(66) = '0') AND (Product6_mul_temp(65) /= '0') ELSE
      "1000000000000000000000000000000000000000000000" WHEN (Product6_mul_temp(66) = '1') AND (Product6_mul_temp(65) /= '1') ELSE
      Product6_mul_temp(65 DOWNTO 20);

  
  LUT_Z24b_k <= to_unsigned(16#00#, 5) WHEN Gvar3_N_unsigned = to_unsigned(16#00#, 5) ELSE
      to_unsigned(16#1F#, 5) WHEN Gvar3_N_unsigned = to_unsigned(16#1F#, 5) ELSE
      Gvar3_N_unsigned;
  LUT_Z24b_out1 <= LUT_Z24b_data(to_integer(LUT_Z24b_k));

  Mult_delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Mult_delay1_out1 <= to_signed(16#00000#, 20);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Mult_delay1_out1 <= LUT_Z24b_out1;
      END IF;
    END IF;
  END PROCESS Mult_delay1_process;


  Delay_Mod10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Delay_Mod10_out1 <= to_signed(0, 46);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Delay_Mod10_out1 <= Z24_in_signed;
      END IF;
    END IF;
  END PROCESS Delay_Mod10_process;


  Product7_mul_temp <= Delay_Mod10_out1 * Mult_delay2_out1;
  
  Product7_out1 <= "0111111111111111111111111111111111111111111111" WHEN (Product7_mul_temp(66) = '0') AND (Product7_mul_temp(65) /= '0') ELSE
      "1000000000000000000000000000000000000000000000" WHEN (Product7_mul_temp(66) = '1') AND (Product7_mul_temp(65) /= '1') ELSE
      Product7_mul_temp(65 DOWNTO 20);

  Delay_Mod11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Delay_Mod11_out1 <= to_signed(0, 46);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Delay_Mod11_out1 <= Sum4_out1;
      END IF;
    END IF;
  END PROCESS Delay_Mod11_process;


  Product8_mul_temp <= Mult_delay1_out1 * Delay_Mod11_out1;
  
  Product8_out1 <= "0111111111111111111111111111111111111111111111" WHEN (Product8_mul_temp(65) = '0') AND (Product8_mul_temp(64) /= '0') ELSE
      "1000000000000000000000000000000000000000000000" WHEN (Product8_mul_temp(65) = '1') AND (Product8_mul_temp(64) /= '1') ELSE
      Product8_mul_temp(64 DOWNTO 19);

  Sum4_stage2_sub_cast <= resize(Product6_out1, 58);
  Sum4_stage2_sub_cast_1 <= resize(Product8_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 58);
  Sum4_op_stage2 <= Sum4_stage2_sub_cast - Sum4_stage2_sub_cast_1;

  Sum4_stage3_add_cast <= resize(Sum4_op_stage2, 59);
  Sum4_stage3_add_cast_1 <= resize(Product7_out1, 58);
  Sum4_stage3_add_cast_2 <= resize(Sum4_stage3_add_cast_1, 59);
  Sum4_stage3_add_temp <= Sum4_stage3_add_cast + Sum4_stage3_add_cast_2;
  
  Sum4_stage3_cast <= "0111111111111111111111111111111111111111111111111111111111" WHEN (Sum4_stage3_add_temp(58) = '0') AND (Sum4_stage3_add_temp(57) /= '0') ELSE
      "1000000000000000000000000000000000000000000000000000000000" WHEN (Sum4_stage3_add_temp(58) = '1') AND (Sum4_stage3_add_temp(57) /= '1') ELSE
      Sum4_stage3_add_temp(57 DOWNTO 0);
  
  Sum4_out1 <= "0111111111111111111111111111111111111111111111" WHEN (Sum4_stage3_cast(57) = '0') AND (Sum4_stage3_cast(56) /= '0') ELSE
      "1000000000000000000000000000000000000000000000" WHEN (Sum4_stage3_cast(57) = '1') AND (Sum4_stage3_cast(56) /= '1') ELSE
      Sum4_stage3_cast(56 DOWNTO 11);

  Z24_out <= std_logic_vector(Sum4_out1);

END rtl;

