-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Der_Faux_FPGA_V2_optimized\Der_Faux_FPGA_tc.vhd
-- Created: 2022-04-19 09:51:10
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Der_Faux_FPGA_tc
-- Source Path: Der_Faux_FPGA_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_128_0 : 128x slower than clk with last phase
-- enb_1_128_1 : 128x slower than clk with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Der_Faux_FPGA_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_128_0                       :   OUT   std_logic;
        enb_1_128_1                       :   OUT   std_logic
        );
END Der_Faux_FPGA_tc;


ARCHITECTURE rtl OF Der_Faux_FPGA_tc IS

  -- Signals
  SIGNAL count128                         : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL phase_all                        : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;

BEGIN
  Counter128 : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      count128 <= to_unsigned(1, 7);
    ELSIF rising_edge(clk) THEN
      IF clk_enable = '1' THEN
        IF count128 >= to_unsigned(127, 7) THEN
          count128 <= to_unsigned(0, 7);
        ELSE
          count128 <= count128 + to_unsigned(1, 7);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter128;

  phase_all <= '1' WHEN clk_enable = '1' ELSE '0';

  temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      phase_0 <= '0';
    ELSIF rising_edge(clk) THEN
      IF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  phase_0_tmp <= '1' WHEN count128 = to_unsigned(127, 7) AND clk_enable = '1' ELSE '0';

  temp_process2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      phase_1 <= '1';
    ELSIF rising_edge(clk) THEN
      IF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process2;

  phase_1_tmp <= '1' WHEN count128 = to_unsigned(0, 7) AND clk_enable = '1' ELSE '0';

  enb <=  phase_all AND clk_enable;

  enb_1_128_0 <=  phase_0 AND clk_enable;

  enb_1_128_1 <=  phase_1 AND clk_enable;


END rtl;

