-- -------------------------------------------------------------
-- 
-- File Name: E:\Users\Donut\Dokumente\FHNW\7. Semester\pro7E\Matlab\2021a\hdl_coder\Der_Faux_FPGA_ovs150_WL46\Z25_circuit.vhd
-- Created: 2020-12-24 12:43:09
-- 
-- Generated by MATLAB 9.10 and HDL Coder 3.18
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Z25_circuit
-- Source Path: Der_Faux_FPGA_ovs150_WL46/Der_Faux_FPGA/Z25_circuit
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Der_Faux_FPGA_pkg.ALL;

ENTITY Z25_circuit IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Gvar2_N                           :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        Z25_in                            :   IN    std_logic_vector(45 DOWNTO 0);  -- sfix46_En49
        Z25_out                           :   OUT   std_logic_vector(45 DOWNTO 0)  -- sfix46_En41
        );
END Z25_circuit;


ARCHITECTURE rtl OF Z25_circuit IS

  -- Constants
  CONSTANT LUT_Z25a_data                  : vector_of_signed21(0 TO 31) := 
    (to_signed(16#082B48#, 21), to_signed(16#082B47#, 21), to_signed(16#082B45#, 21), to_signed(16#082B43#, 21),
     to_signed(16#082B40#, 21), to_signed(16#082B3E#, 21), to_signed(16#082B3B#, 21), to_signed(16#082B39#, 21),
     to_signed(16#082B36#, 21), to_signed(16#082B32#, 21), to_signed(16#082B2F#, 21), to_signed(16#082B2B#, 21),
     to_signed(16#082B27#, 21), to_signed(16#082B22#, 21), to_signed(16#082B1D#, 21), to_signed(16#082B17#, 21),
     to_signed(16#082B10#, 21), to_signed(16#082B09#, 21), to_signed(16#082B00#, 21), to_signed(16#082AF6#, 21),
     to_signed(16#082AEB#, 21), to_signed(16#082ADD#, 21), to_signed(16#082ACC#, 21), to_signed(16#082AB8#, 21),
     to_signed(16#082A9F#, 21), to_signed(16#082A7F#, 21), to_signed(16#082A54#, 21), to_signed(16#082A18#, 21),
     to_signed(16#0829BE#, 21), to_signed(16#082928#, 21), to_signed(16#0827FC#, 21), to_signed(16#08247A#, 21));  -- sfix21 [32]
  CONSTANT LUT_Z25b_data                  : vector_of_signed20(0 TO 31) := 
    (to_signed(-16#7FF92#, 20), to_signed(-16#7FF8E#, 20), to_signed(-16#7FF8A#, 20), to_signed(-16#7FF86#, 20),
     to_signed(-16#7FF82#, 20), to_signed(-16#7FF7D#, 20), to_signed(-16#7FF78#, 20), to_signed(-16#7FF73#, 20),
     to_signed(-16#7FF6D#, 20), to_signed(-16#7FF66#, 20), to_signed(-16#7FF5F#, 20), to_signed(-16#7FF58#, 20),
     to_signed(-16#7FF4F#, 20), to_signed(-16#7FF46#, 20), to_signed(-16#7FF3C#, 20), to_signed(-16#7FF30#, 20),
     to_signed(-16#7FF23#, 20), to_signed(-16#7FF14#, 20), to_signed(-16#7FF04#, 20), to_signed(-16#7FEF0#, 20),
     to_signed(-16#7FEDA#, 20), to_signed(-16#7FEBF#, 20), to_signed(-16#7FE9F#, 20), to_signed(-16#7FE78#, 20),
     to_signed(-16#7FE46#, 20), to_signed(-16#7FE07#, 20), to_signed(-16#7FDB3#, 20), to_signed(-16#7FD3E#, 20),
     to_signed(-16#7FC8D#, 20), to_signed(-16#7FB67#, 20), to_signed(-16#7F91C#, 20), to_signed(-16#7F23E#, 20));  -- sfix20 [32]

  -- Signals
  SIGNAL Gvar2_N_unsigned                 : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL LUT_Z25a_k                       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL LUT_Z25a_out1                    : signed(20 DOWNTO 0);  -- sfix21_En19
  SIGNAL Mult_delay2_out1                 : signed(20 DOWNTO 0);  -- sfix21_En19
  SIGNAL Z25_in_signed                    : signed(45 DOWNTO 0);  -- sfix46_En49
  SIGNAL Product6_mul_temp                : signed(66 DOWNTO 0);  -- sfix67_En68
  SIGNAL Product6_out1                    : signed(45 DOWNTO 0);  -- sfix46_En49
  SIGNAL LUT_Z25b_k                       : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL LUT_Z25b_out1                    : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL Mult_delay1_out1                 : signed(19 DOWNTO 0);  -- sfix20_En19
  SIGNAL Delay_Mod10_out1                 : signed(45 DOWNTO 0);  -- sfix46_En49
  SIGNAL Product7_mul_temp                : signed(66 DOWNTO 0);  -- sfix67_En68
  SIGNAL Product7_out1                    : signed(45 DOWNTO 0);  -- sfix46_En49
  SIGNAL Sum4_out1                        : signed(45 DOWNTO 0);  -- sfix46_En41
  SIGNAL Delay_Mod11_out1                 : signed(45 DOWNTO 0);  -- sfix46_En41
  SIGNAL Product8_mul_temp                : signed(65 DOWNTO 0);  -- sfix66_En60
  SIGNAL Product8_out1                    : signed(45 DOWNTO 0);  -- sfix46_En41
  SIGNAL Sum4_stage2_sub_cast             : signed(54 DOWNTO 0);  -- sfix55_En49
  SIGNAL Sum4_stage2_sub_cast_1           : signed(54 DOWNTO 0);  -- sfix55_En49
  SIGNAL Sum4_op_stage1                   : signed(54 DOWNTO 0);  -- sfix55_En49
  SIGNAL Sum4_stage3_add_cast             : signed(55 DOWNTO 0);  -- sfix56_En49
  SIGNAL Sum4_stage3_add_cast_1           : signed(54 DOWNTO 0);  -- sfix55_En49
  SIGNAL Sum4_stage3_add_cast_2           : signed(55 DOWNTO 0);  -- sfix56_En49
  SIGNAL Sum4_stage3_add_temp             : signed(55 DOWNTO 0);  -- sfix56_En49
  SIGNAL Sum4_stage3_cast                 : signed(54 DOWNTO 0);  -- sfix55_En49

BEGIN
  Gvar2_N_unsigned <= unsigned(Gvar2_N);

  
  LUT_Z25a_k <= to_unsigned(16#00#, 5) WHEN Gvar2_N_unsigned = to_unsigned(16#00#, 5) ELSE
      to_unsigned(16#1F#, 5) WHEN Gvar2_N_unsigned = to_unsigned(16#1F#, 5) ELSE
      Gvar2_N_unsigned;
  LUT_Z25a_out1 <= LUT_Z25a_data(to_integer(LUT_Z25a_k));

  Mult_delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Mult_delay2_out1 <= to_signed(16#000000#, 21);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Mult_delay2_out1 <= LUT_Z25a_out1;
      END IF;
    END IF;
  END PROCESS Mult_delay2_process;


  Z25_in_signed <= signed(Z25_in);

  Product6_mul_temp <= Mult_delay2_out1 * Z25_in_signed;
  
  Product6_out1 <= "0111111111111111111111111111111111111111111111" WHEN (Product6_mul_temp(66) = '0') AND (Product6_mul_temp(65 DOWNTO 64) /= "00") ELSE
      "1000000000000000000000000000000000000000000000" WHEN (Product6_mul_temp(66) = '1') AND (Product6_mul_temp(65 DOWNTO 64) /= "11") ELSE
      Product6_mul_temp(64 DOWNTO 19);

  
  LUT_Z25b_k <= to_unsigned(16#00#, 5) WHEN Gvar2_N_unsigned = to_unsigned(16#00#, 5) ELSE
      to_unsigned(16#1F#, 5) WHEN Gvar2_N_unsigned = to_unsigned(16#1F#, 5) ELSE
      Gvar2_N_unsigned;
  LUT_Z25b_out1 <= LUT_Z25b_data(to_integer(LUT_Z25b_k));

  Mult_delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Mult_delay1_out1 <= to_signed(16#00000#, 20);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Mult_delay1_out1 <= LUT_Z25b_out1;
      END IF;
    END IF;
  END PROCESS Mult_delay1_process;


  Delay_Mod10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Delay_Mod10_out1 <= to_signed(0, 46);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Delay_Mod10_out1 <= Z25_in_signed;
      END IF;
    END IF;
  END PROCESS Delay_Mod10_process;


  Product7_mul_temp <= Delay_Mod10_out1 * Mult_delay2_out1;
  
  Product7_out1 <= "0111111111111111111111111111111111111111111111" WHEN (Product7_mul_temp(66) = '0') AND (Product7_mul_temp(65 DOWNTO 64) /= "00") ELSE
      "1000000000000000000000000000000000000000000000" WHEN (Product7_mul_temp(66) = '1') AND (Product7_mul_temp(65 DOWNTO 64) /= "11") ELSE
      Product7_mul_temp(64 DOWNTO 19);

  Delay_Mod11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      Delay_Mod11_out1 <= to_signed(0, 46);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Delay_Mod11_out1 <= Sum4_out1;
      END IF;
    END IF;
  END PROCESS Delay_Mod11_process;


  Product8_mul_temp <= Mult_delay1_out1 * Delay_Mod11_out1;
  
  Product8_out1 <= "0111111111111111111111111111111111111111111111" WHEN (Product8_mul_temp(65) = '0') AND (Product8_mul_temp(64) /= '0') ELSE
      "1000000000000000000000000000000000000000000000" WHEN (Product8_mul_temp(65) = '1') AND (Product8_mul_temp(64) /= '1') ELSE
      Product8_mul_temp(64 DOWNTO 19);

  Sum4_stage2_sub_cast <= resize(Product6_out1, 55);
  Sum4_stage2_sub_cast_1 <= resize(Product8_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 55);
  Sum4_op_stage1 <= Sum4_stage2_sub_cast - Sum4_stage2_sub_cast_1;

  Sum4_stage3_add_cast <= resize(Sum4_op_stage1, 56);
  Sum4_stage3_add_cast_1 <= resize(Product7_out1, 55);
  Sum4_stage3_add_cast_2 <= resize(Sum4_stage3_add_cast_1, 56);
  Sum4_stage3_add_temp <= Sum4_stage3_add_cast + Sum4_stage3_add_cast_2;
  
  Sum4_stage3_cast <= "0111111111111111111111111111111111111111111111111111111" WHEN (Sum4_stage3_add_temp(55) = '0') AND (Sum4_stage3_add_temp(54) /= '0') ELSE
      "1000000000000000000000000000000000000000000000000000000" WHEN (Sum4_stage3_add_temp(55) = '1') AND (Sum4_stage3_add_temp(54) /= '1') ELSE
      Sum4_stage3_add_temp(54 DOWNTO 0);
  
  Sum4_out1 <= "0111111111111111111111111111111111111111111111" WHEN (Sum4_stage3_cast(54) = '0') AND (Sum4_stage3_cast(53) /= '0') ELSE
      "1000000000000000000000000000000000000000000000" WHEN (Sum4_stage3_cast(54) = '1') AND (Sum4_stage3_cast(53) /= '1') ELSE
      Sum4_stage3_cast(53 DOWNTO 8);

  Z25_out <= std_logic_vector(Sum4_out1);

END rtl;

